[package]
name = "brumble-server"
version = "0.1.0"
authors = ["Adam Thibert <adamthibert01@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
brumble-commons = { path = "../commons" }
